"use client";
import { useEffect,useState,useRef } from "react";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { Table,TableHeader,TableRow,TableHead,TableBody,TableCell } from "@/components/ui/table";
import { BookOpen,Target,Timer,Plus,ArrowUpRight,Check,NotebookPen,Activity } from "lucide-react";
import curriculum from "./curriculum.json";
const heroes=["Mina","Warden","Abrams","Pocket"];
const phases=["Mechanics & lane control","Economy & map decisions","Combat & conversion","Advanced adaptation"];
const statuses=["Not started","Studying","Practicing","Gate passed"];
type Session={id:string,date:string,hero:string,lesson:number,minutes:number,matches:number,successes:number,opportunities:number,focus:number,notes:string,matchId:string,patch:string};
type LessonState={id:number,status:string,notes:string};
type Data={sessions:Session[],lessons:LessonState[]};
const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
function Picker({label,value,onChange,items}:{label:string,value:string,onChange:(v:string)=>void,items:{value:string,label:string}[]}) {return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></div>}
function Html({value}:{value:string}){return <div className="reading" dangerouslySetInnerHTML={{__html:value}}/>}
export default function Home(){
 const [tab,setTab]=useState("dashboard"),[data,setData]=useState<Data>({sessions:[],lessons:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState(""),[busy,setBusy]=useState(false),[auth,setAuth]=useState(false);
 const [selected,setSelected]=useState(1),[phase,setPhase]=useState("all"),[hero,setHero]=useState("Mina"),[section,setSection]=useState("0");
 const [lessonDraft,setLessonDraft]=useState<LessonState>({id:1,status:"Not started",notes:""}),[dialog,setDialog]=useState(false),[formError,setFormError]=useState(""),[lessonError,setLessonError]=useState("");
 const empty=():Session=>({id:crypto.randomUUID(),date:localDay(),hero,lesson:selected,minutes:30,matches:0,successes:0,opportunities:0,focus:3,notes:"",matchId:"",patch:""});
 const [form,setForm]=useState<Session|null>(null);const current=useRef(data);current.current=data;
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch('/api/training',{cache:'no-store'});const d=await r.json() as Data & {error?:string};if(!r.ok){setAuth(r.status===401);throw Error(d.error??"Could not load progress.")}setAuth(false);setData(d);}catch(e){setError(e instanceof Error?e.message:"Could not load progress.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{setLessonDraft(data.lessons.find(l=>l.id===selected)??{id:selected,status:"Not started",notes:""})},[selected,data.lessons]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();
 const register=(t:any)=>{try{Promise.resolve(context.registerTool(t,{signal:c.signal})).catch(()=>{})}catch{}};
 register({name:"read_training_progress",description:"Read saved lesson statuses and training sessions currently loaded in this app.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({loaded:!loading,error:error||null,...current.current})});
 register({name:"open_training_lesson",description:"Open a lesson for study. This does not mark it complete or change saved progress.",inputSchema:{type:"object",properties:{lessonId:{type:"integer",minimum:1,maximum:24}},required:["lessonId"],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!Number.isInteger(input?.lessonId)||input.lessonId<1||input.lessonId>24)throw Error("Choose a lesson from 1 to 24.");setSelected(input.lessonId);setTab("lessons");await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {openedLesson:input.lessonId}}});return()=>c.abort();},[loading,error]);
 const persist=async(kind:string,value:Session|LessonState)=>{const r=await fetch('/api/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data:value})});const d=await r.json() as {data:any,error?:string};if(!r.ok)throw Error(d.error??"Could not save.");setData(prev=>kind==='session'?{...prev,sessions:[d.data,...prev.sessions.filter(s=>s.id!==value.id)]}:{...prev,lessons:[d.data,...prev.lessons.filter(l=>l.id!==value.id)]});setSaved("Saved to your progress");};
 const saveLesson=async()=>{setBusy(true);setLessonError("");setSaved("");try{await persist('lesson',lessonDraft)}catch(e){setLessonError((e as Error).message)}finally{setBusy(false)}};
 const saveSession=async(e:React.FormEvent)=>{e.preventDefault();if(!form)return;setFormError("");if(form.successes>form.opportunities){setFormError("Successes cannot exceed opportunities.");return}setBusy(true);try{await persist('session',form);setDialog(false)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}};
 const openLog=(s?:Session)=>{setForm(s??empty());setFormError("");setSaved("");setDialog(true)};
 const lesson=curriculum.lessons.find(l=>l.id===selected)!;
 const passed=data.lessons.filter(l=>l.status==='Gate passed').length;
 const active=data.lessons.filter(l=>l.status==='Practicing'||l.status==='Studying').length;
 const sessions=[...data.sessions].sort((a,b)=>b.date.localeCompare(a.date));
 const totalMinutes=sessions.reduce((n,s)=>n+s.minutes,0);
 const recommended=curriculum.lessons.find(l=>data.lessons.find(p=>p.id===l.id)?.status==='Practicing')??curriculum.lessons.find(l=>data.lessons.find(p=>p.id===l.id)?.status!=='Gate passed')??curriculum.lessons[0];
 const lessonSessions=sessions.filter(s=>s.lesson===selected);
 const opportunities=lessonSessions.reduce((n,s)=>n+s.opportunities,0),successes=lessonSessions.reduce((n,s)=>n+s.successes,0);
 const showLesson=(id:number)=>{setSelected(id);setTab('lessons');setSaved('')};
 const field=(key:keyof Session,value:string|number)=>setForm(p=>p?{...p,[key]:value}:p);
 const weekBars=Array.from({length:6},(_,i)=>{const end=new Date();end.setHours(23,59,59,999);end.setDate(end.getDate()-(5-i)*7);const start=new Date(end);start.setDate(start.getDate()-6);start.setHours(0,0,0,0);return {label:start.toLocaleDateString(undefined,{month:'short',day:'numeric'}),minutes:sessions.filter(s=>new Date(s.date+'T12:00:00')>=start&&new Date(s.date+'T12:00:00')<=end).reduce((n,s)=>n+s.minutes,0)}});
 const maxBar=Math.max(60,...weekBars.map(b=>b.minutes));
 return <div className="app-shell">
  <header className="masthead"><a href="/" className="brand"><span className="monogram">E</span><span>DEADLOCK<span className="brand-sub">TRAINING JOURNAL</span></span></a><span className="private-label">PERSONAL TRAINING / MARK</span><button className="primary" onClick={()=>openLog()} disabled={loading||!!error}><Plus size={18}/> Log a session</button></header>
  <main><div className="page-title"><div><p className="eyebrow">THE LONG GAME</p><h1>Road to Eternus<span>.</span></h1></div><p className="intro">One skill. Deliberate practice.<br/>Evidence you can build on.</p></div>
  <Tabs value={tab} onValueChange={setTab}>
   <TabsList className="main-tabs" aria-label="Training views">{[['dashboard','Overview'],['lessons','24 lessons'],['heroes','Hero practice'],['journal','Session journal'],['guide','Study guide']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList>
   {loading&&<p className="notice" role="status">Loading your saved progress…</p>}
   {error&&<div className="error" role="alert">{error} {auth?<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>:<button onClick={()=>void load()}>Retry loading</button>}</div>}
   {saved&&<p className="save-message" role="status"><Check size={16}/>{saved}</p>}
   <TabsContent value="dashboard">
    <div className="stats-grid">
     <div className="stat"><span><BookOpen size={17}/> Lesson gates passed</span><strong>{loading||error?'—':passed}<small> / 24</small></strong><Progress value={passed/24*100} aria-label="Lesson gates passed"/></div>
     <div className="stat"><span><Timer size={17}/> Practice logged</span><strong>{loading||error?'—':(totalMinutes/60).toFixed(1)}<small> hours</small></strong><p>{sessions.length} saved sessions</p></div>
     <div className="stat"><span><Target size={17}/> In progress</span><strong>{loading||error?'—':active}<small> lessons</small></strong><p>Study → practice → demonstrate</p></div>
    </div>
    <div className="dashboard-grid"><section className="next-card"><p className="eyebrow">{passed===24?'RETEST & RETAIN':'YOUR NEXT REP'} / LESSON {String(recommended.id).padStart(2,'0')}</p><h2>{recommended.title}</h2><blockquote>{recommended.cue}</blockquote><div className="next-actions"><button className="primary" onClick={()=>showLesson(recommended.id)}>Open lesson <ArrowUpRight size={18}/></button><span>{phases[recommended.phase-1]}</span></div></section>
     <section className="panel"><div className="section-label"><h2>Practice rhythm</h2><span>Last 6 weeks</span></div><div className="bar-chart" role="img" aria-label={weekBars.map(b=>`${b.label}: ${b.minutes} minutes`).join('; ')}>{weekBars.map(b=><div className="bar-column" key={b.label}><span>{b.minutes?`${b.minutes}m`:'—'}</span><div className="bar-track"><div style={{height:`${b.minutes/maxBar*100}%`}}/></div><span>{b.label}</span></div>)}</div><p className="muted">Logged practice time, not a skill rating.</p></section>
    </div>
    <div className="section-label"><h2>Your four-hero pool</h2><span>Focus on two per training block</span></div>
    <div className="hero-grid">{heroes.map((name,i)=>{const ss=sessions.filter(s=>s.hero===name);return <button className={'hero-card hero-'+i} key={name} onClick={()=>{setHero(name);setTab('heroes')}}><span className="hero-index">0{i+1}</span><h3>{name}</h3><p>{['Commitment & finishing','Pressure & setup','Space & control','Sequencing & escape'][i]}</p><span>{ss.length} sessions · {(ss.reduce((n,s)=>n+s.minutes,0)/60).toFixed(1)}h <ArrowUpRight size={16}/></span></button>})}</div>
    <section className="footnote"><Target size={20}/><p><strong>Progress means demonstrated habits.</strong> Mark a gate passed only after you have evidence from the lesson’s assessment. These targets do not predict your rank. Player data can be added later.</p></section>
   </TabsContent>
   <TabsContent value="lessons"><div className="lesson-layout"><aside className="lesson-nav"><Picker label="Training phase" value={phase} onChange={setPhase} items={[{value:'all',label:'All 24 lessons'},...phases.map((p,i)=>({value:String(i+1),label:p}))]}/><div className="lesson-list">{curriculum.lessons.filter(l=>phase==='all'||l.phase===Number(phase)).map(l=><button key={l.id} className={selected===l.id?'selected':''} onClick={()=>{setSelected(l.id);setSaved('')}}><span className="lesson-number">{String(l.id).padStart(2,'0')}</span><span>{l.title}<small>{data.lessons.find(x=>x.id===l.id)?.status??'Not started'}</small></span>{data.lessons.find(x=>x.id===l.id)?.status==='Gate passed'&&<Check size={16}/>}</button>)}</div></aside><article className="panel lesson-detail"><p className="eyebrow">PHASE {lesson.phase} / LESSON {String(selected).padStart(2,'0')}</p><h2 className="article-title">{lesson.title}</h2><Html value={lesson.html}/><div className="tracker"><h3>Track this lesson</h3><p className="muted">Read it, apply it, then use the assessment to judge transfer.</p><Picker label="Lesson status" value={lessonDraft.status} onChange={v=>setLessonDraft({...lessonDraft,status:v})} items={statuses.map(v=>({value:v,label:v}))}/><label>Evidence & next correction<textarea value={lessonDraft.notes} maxLength={6000} onChange={e=>setLessonDraft({...lessonDraft,notes:e.target.value})} placeholder="Match timestamp, what you demonstrated, and what to change next…"/></label><div className="button-row">{lessonError&&<p className="error" role="alert">{lessonError}</p>}<button className="primary" disabled={busy||loading||!!error} onClick={()=>void saveLesson()}>{busy?'Saving…':'Save lesson progress'}</button><button className="secondary" disabled={loading||!!error} onClick={()=>openLog()}>Log practice</button></div><p className="muted">{lessonSessions.length} related sessions · {opportunities?`${Math.round(successes/opportunities*100)}% (${successes}/${opportunities}) successful opportunities`:'No assessed opportunities yet'}</p></div></article></div></TabsContent>
   <TabsContent value="heroes"><div className="hero-practice"><div><Picker label="Hero" value={hero} onChange={setHero} items={heroes.map(v=>({value:v,label:v}))}/><section className="panel hero-summary"><p className="eyebrow">PRACTICE RECORD</p><h2>{hero}</h2><strong className="large-number">{sessions.filter(s=>s.hero===hero).length}</strong><p>sessions logged</p><button className="primary" onClick={()=>openLog()} disabled={loading||!!error}>Log {hero} practice</button><p className="muted">Keep one decision goal per session. The full hero track is your menu, not a checklist to complete in every match.</p></section></div><article className="panel"><p className="eyebrow">HERO SPECIALIZATION</p><h2 className="article-title">{curriculum.heroes.find(h=>h.name===hero)?.title}</h2><Html value={curriculum.heroes.find(h=>h.name===hero)!.html}/></article></div></TabsContent>
   <TabsContent value="journal"><div className="section-label"><div><h2>Your practice, with evidence</h2><p className="muted">Log games, drills, or replay study. Reopen an entry to correct it.</p></div><button className="primary" disabled={loading||!!error} onClick={()=>openLog()}><Plus size={17}/> Log a session</button></div>{sessions.length===0?<section className="empty-state"><NotebookPen size={38}/><h3>Your first session starts the record.</h3><p>Choose a hero and lesson, record your practice, and capture one correction for next time.</p><button className="secondary" onClick={()=>openLog()} disabled={loading||!!error}>Add first session</button></section>:<section className="panel journal-panel"><Table><TableHeader><TableRow>{['Date / hero','Lesson','Practice','Application','Notes',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{sessions.map(s=><TableRow key={s.id}><TableCell><strong>{s.hero}</strong><small className="block-muted">{s.date}</small></TableCell><TableCell>{s.lesson}. {curriculum.lessons[s.lesson-1].title}</TableCell><TableCell>{s.minutes} min<small className="block-muted">{s.matches} matches · focus {s.focus}/5</small></TableCell><TableCell>{s.opportunities?`${s.successes}/${s.opportunities}`:'Not assessed'}</TableCell><TableCell><p className="journal-note">{s.notes||'No notes'}</p>{s.matchId&&<small className="block-muted">Match: {s.matchId}</small>}{s.patch&&<small className="block-muted">Patch: {s.patch}</small>}</TableCell><TableCell><button className="text-button" onClick={()=>openLog(s)} disabled={loading||!!error}>Edit</button></TableCell></TableRow>)}</TableBody></Table></section>}</TabsContent>
   <TabsContent value="guide"><div className="guide-toolbar"><Picker label="Guide section" value={section} onChange={setSection} items={curriculum.sections.map((s,i)=>({value:String(i),label:s.title}))}/><a href="/Deadlock_Eternus_Training_Guide.md" download className="secondary">Download full guide</a></div><article className="panel full-guide"><h2 className="article-title">{curriculum.sections[Number(section)].title}</h2><Html value={curriculum.sections[Number(section)].html}/></article></TabsContent>
  </Tabs>
  <footer><span>ROAD TO ETERNUS</span><span>Manual training records · Mina / Warden / Abrams / Pocket</span></footer>
  </main>
  <Dialog open={dialog} onOpenChange={v=>{if(!busy)setDialog(v)}}><DialogContent className="session-dialog"><DialogTitle className="dialog-title">{form&&sessions.some(s=>s.id===form.id)?'Edit session':'Log a training session'}</DialogTitle><DialogDescription>Record what you practiced and what the next session should change.</DialogDescription>{form&&<form onSubmit={saveSession} className="session-form"><div className="form-grid"><label>Date<input type="date" required value={form.date} onChange={e=>field('date',e.target.value)}/></label><Picker label="Hero" value={form.hero} onChange={v=>field('hero',v)} items={heroes.map(v=>({value:v,label:v}))}/></div><Picker label="Lesson practiced" value={String(form.lesson)} onChange={v=>field('lesson',Number(v))} items={curriculum.lessons.map(l=>({value:String(l.id),label:`${l.id}. ${l.title}`}))}/><div className="form-grid"><label>Minutes<input type="number" min={1} max={1440} required value={form.minutes} onChange={e=>field('minutes',Number(e.target.value))}/></label><label>Matches played<input type="number" min={0} max={100} required value={form.matches} onChange={e=>field('matches',Number(e.target.value))}/></label></div><div className="form-grid"><label>Successful applications<input type="number" min={0} max={10000} required value={form.successes} onChange={e=>field('successes',Number(e.target.value))}/></label><label>Opportunities assessed<input type="number" min={0} max={10000} required value={form.opportunities} onChange={e=>field('opportunities',Number(e.target.value))}/></label></div><p className="muted">Use 0 / 0 when you did not assess opportunities. Count a specific behavior, not wins.</p><Picker label="Focus during practice" value={String(form.focus)} onChange={v=>field('focus',Number(v))} items={[1,2,3,4,5].map(v=>({value:String(v),label:`${v} / 5${v===1?' — Distracted':v===5?' — Fully focused':''}`}))}/><div className="form-grid"><label>Match ID / timestamp (optional)<input value={form.matchId} maxLength={120} onChange={e=>field('matchId',e.target.value)}/></label><label>Patch / queue (optional)<input value={form.patch} maxLength={80} onChange={e=>field('patch',e.target.value)}/></label></div><label>Evidence & next correction<textarea value={form.notes} maxLength={6000} onChange={e=>field('notes',e.target.value)} placeholder="What worked? What will you change next time?"/></label>{formError&&<p className="error" role="alert">{formError}</p>}<button type="submit" className="primary" disabled={busy}>{busy?'Saving…':'Save session'}</button></form>}</DialogContent></Dialog>
 </div>
}
